/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
  id INTEGER,
  name VARCHAR(255),
  date_of_birth DATE,
  escape_attempts INTEGER,
  neutered BOOLEAN,
  weight_kg DECIMAL(10,2)
);

ALTER TABLE animals ADD COLUMN species VARCHAR(100);

CREATE TABLE owners (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(100),
  age INTEGER
);

CREATE TABLE species (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100)
);

ALTER TABLE animals DROP COLUMN species;

ALTER TABLE animals ADD COLUMN species_id INTEGER REFERENCES species(id);

ALTER TABLE animals ADD COLUMN owner_id INTEGER REFERENCES owners(id);

-- Create a table named vets
CREATE TABLE vets (
id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
name varchar(100),
age integer,
date_of_graduation date,
PRIMARY KEY (id)
);

-- Create a "join table" called visits
CREATE TABLE visits (
animal_id INTEGER,
vet_id INTEGER,
date_of_visit DATE,
CONSTRAINT fk_animals FOREIGN KEY (animal_id) REFERENCES animals(id),
CONSTRAINT fk_vets FOREIGN KEY (vet_id) REFERENCES vets(id)
);
SELECT * FROM visits;

-- Create a "join table" called specializations
CREATE TABLE specializations (
spec_id INTEGER,
vet_id INTEGER,
CONSTRAINT fk_vets FOREIGN KEY (vet_id) REFERENCES vets(id),
CONSTRAINT fk_species FOREIGN KEY (spec_id) REFERENCES species(id)
);
SELECT * FROM specializations;

-- Add an email column to your owners table
ALTER TABLE owners ADD COLUMN email VARCHAR(120);

-- Create indexes to optimize queries
CREATE INDEX id_btree ON visits USING btree(animal_id) WHERE animal_id = 4;

CREATE INDEX vets_asc ON visits(vet_id asc) INCLUDE (animal_id, date_of_visit);

CREATE INDEX owners_asc ON owners(email desc) INCLUDE (id, full_name, age);

-- Add email column to owners table
ALTER TABLE animals ADD COLUMN email VARCHAR(120);
